//
//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16yShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.11750 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.16927 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.11750 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.06573 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.11750 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.32436 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.37613 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.22096 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.16919 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.32436 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.58280 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.63457 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.53117 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.47940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.58280 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.63445 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.78962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.73785 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.58268 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.63445 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.22099 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.27276 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.11759 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.06582 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.22099 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.47943 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.53120 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.42780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.37603 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.47943 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.53108 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.68625 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.63448 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.47931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.53108 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.84131 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.89308 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.84131 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.78954 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.84131 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.27276 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.22099 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.06582 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.11759 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.27276 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.42762 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.47939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.42762 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.37585 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.42762 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.63448 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.68625 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.53108 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.47931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.63448 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.89292 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.94469 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.84129 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.78952 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.89292 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.16911 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.22088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.11748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.06571 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.16911 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.22096 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.37613 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.32436 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.16919 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.22096 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.53119 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.58296 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.53119 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.47942 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.53119 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.73785 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.78962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.63445 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.58268 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.73785 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.06580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.22097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.16920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.01403 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.06580 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.27266 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.32443 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.27266 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.22089 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.27266 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.58289 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.63466 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.47949 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.42772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.58289 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.73796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.78973 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.68633 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.63456 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.73796 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.16929 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.22106 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.16929 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.11752 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.16929 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.47932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.53109 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.37592 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.32415 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.47932 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.63458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.68636 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.58295 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.53118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.63458 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.78961 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.94478 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.89301 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.73784 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.78961 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.27248 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.32425 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.22085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.16908 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.27248 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.32433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.47950 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.42773 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.27256 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.32433 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.63456 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.68633 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.63456 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.58279 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.63456 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.84142 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.89319 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.73802 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.68625 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.84142 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.37605 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.42782 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.32442 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.27265 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.37605 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.42770 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.58288 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.53110 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.37593 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.42770 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.73794 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.78971 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.73794 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.68617 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.73794 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.94480 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.99657 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.84140 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.78962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.94480 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.06571 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.11748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.06571 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.01394 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.06571 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.42772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.27255 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.22078 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.37595 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.42772 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.53101 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.58278 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.47938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.42761 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.53101 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.68624 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.84141 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.78964 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.63447 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.68624 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.32434 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.16917 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.11740 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.27257 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.32434 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.42764 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.47941 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.37601 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.32424 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.42764 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.58286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.73803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.68626 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.53109 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.58286 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.78972 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.84149 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.78972 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.73795 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.78972 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.16917 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.32434 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.27257 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.11740 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.16917 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.37603 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.42780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.37603 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.32426 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.37603 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.68626 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.73803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.58286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.53109 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.68626 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.84133 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.89310 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.78970 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.73793 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.84133 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.11752 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.16929 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.06589 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.01412 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.11752 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.27255 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.42772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.37595 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.22078 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.27255 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.47940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.53118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.47940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.42763 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.47940 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.78964 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.84141 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.68624 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.63447 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.78964 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.32425 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.37602 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.32425 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.27248 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.32425 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.53110 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.58288 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.42770 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.37593 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.53110 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.78955 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.84132 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.73792 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.68614 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.78955 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.84140 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.99657 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.94480 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.78962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.84140 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.22087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.27264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26279 * frame.width, y: frame.minY + 0.22087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21018 * frame.width, y: frame.minY + 0.16910 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15757 * frame.width, y: frame.minY + 0.22087 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.42773 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52559 * frame.width, y: frame.minY + 0.47950 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68326 * frame.width, y: frame.minY + 0.32433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63066 * frame.width, y: frame.minY + 0.27256 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47298 * frame.width, y: frame.minY + 0.42773 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.68617 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.26278 * frame.width, y: frame.minY + 0.73794 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36785 * frame.width, y: frame.minY + 0.63454 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31524 * frame.width, y: frame.minY + 0.58277 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21017 * frame.width, y: frame.minY + 0.68617 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.73802 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94578 * frame.width, y: frame.minY + 0.89319 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99838 * frame.width, y: frame.minY + 0.84142 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84071 * frame.width, y: frame.minY + 0.68625 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78810 * frame.width, y: frame.minY + 0.73802 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.22089 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.27266 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.16926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.11749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.22089 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.37592 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.53109 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.47932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.32415 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.37592 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.58278 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.63455 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.58278 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.53101 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.58278 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.89301 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.94478 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.78961 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.73784 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.89301 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.16920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05261 * frame.width, y: frame.minY + 0.22097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21028 * frame.width, y: frame.minY + 0.06580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.15767 * frame.width, y: frame.minY + 0.01403 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.16920 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.32427 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73576 * frame.width, y: frame.minY + 0.37604 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84083 * frame.width, y: frame.minY + 0.27264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78823 * frame.width, y: frame.minY + 0.22087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.32427 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.47949 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47300 * frame.width, y: frame.minY + 0.63466 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52560 * frame.width, y: frame.minY + 0.58289 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.36793 * frame.width, y: frame.minY + 0.42772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31532 * frame.width, y: frame.minY + 0.47949 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.68615 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.73792 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73577 * frame.width, y: frame.minY + 0.68615 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68316 * frame.width, y: frame.minY + 0.63438 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63056 * frame.width, y: frame.minY + 0.68615 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16yLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 1.0)
		
			//// Bezier 17 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.10520 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10520 * frame.width, y: frame.minY + 0.97167 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.42042 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42042 * frame.width, y: frame.minY + 0.97167 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.58217 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58217 * frame.width, y: frame.minY + 0.97167 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.89739 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.89739 * frame.width, y: frame.minY + 0.97167 * frame.height))
		
		return path
	}
}

/*
 func drawCanvas1(frame: CGRect = CGRect(x: 0, y: 0, width: 248, height: 252)) {
 //// Color Declarations
 let strokeColor = UIColor(red: 0.792, green: 0.000, blue: 0.533, alpha: 1.000)
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 
 
 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 
 

 strokeColor.setStroke()
 path.lineWidth = 1
 path.stroke()
 }

 */
