//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16qShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14195 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14195 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78083 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63876 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63876 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28398 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28398 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17743 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17743 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78079 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78079 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67441 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67441 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24832 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24832 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74530 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74530 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99379 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99379 * frame.width, y: frame.minY + 0.25170 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.25170 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35487 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28389 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63876 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63876 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56779 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78082 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14190 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28388 * frame.width, y: frame.minY + 0.33780 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21289 * frame.width, y: frame.minY + 0.51264 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78083 * frame.width, y: frame.minY + 0.68748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70983 * frame.width, y: frame.minY + 0.86232 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14195 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14195 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78087 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07097 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.77195 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.07856 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.85185 * frame.width, y: frame.minY + 0.42526 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28398 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.28398 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24841 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17743 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17743 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14186 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78079 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.78079 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74522 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67441 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67441 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.63884 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24832 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24832 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.51286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17735 * frame.width, y: frame.minY + 0.68765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49681 * frame.width, y: frame.minY + 0.25170 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.25170 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42584 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74530 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74530 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.16286 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67433 * frame.width, y: frame.minY + 0.33765 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99379 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99379 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.59840 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92282 * frame.width, y: frame.minY + 0.94509 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16qLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 300.0 / 120.0)
		
			//// Bezier 17 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.42587 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42587 * frame.width, y: frame.minY + 0.99860 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.49686 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49686 * frame.width, y: frame.minY + 0.99860 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.92281 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92281 * frame.width, y: frame.minY + 0.99860 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.99380 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99380 * frame.width, y: frame.minY + 0.99860 * frame.height))
		
		return path
	}
}
