//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid8jShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 1
			//// Rectangle 6 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.22069 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41261 * rect.width, y: rect.minY + 0.31453 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53046 * rect.width, y: rect.minY + 0.12684 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47153 * rect.width, y: rect.minY + 0.03300 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.22069 * rect.height))
		path.close()
		
			//// Rectangle 8 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76611 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.22066 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64826 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.close()
		
			//// Rectangle 13 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23569 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.31449 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.close()
		
			//// Rectangle 26 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29479 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.59597 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.close()
		
			//// Rectangle 36 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88412 * rect.width, y: rect.minY + 0.68984 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.99810 * rect.width, y: rect.minY + 0.50215 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.94304 * rect.width, y: rect.minY + 0.40831 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.close()
		
			//// Rectangle 43 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70720 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.68980 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58935 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 2
			//// Rectangle 5 Drawing
		path.move(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.22067 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11785 * rect.width, y: rect.minY + 0.40836 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17678 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.05893 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.22067 * rect.height))
		path.close()
		
			//// Rectangle 15 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41262 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.close()
		
			//// Rectangle 22 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82503 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.31449 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70718 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.close()
		
			//// Rectangle 35 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.78367 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64829 * rect.width, y: rect.minY + 0.68982 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53044 * rect.width, y: rect.minY + 0.50213 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 0.59598 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.78367 * rect.height))
		path.close()
		
			//// Rectangle 40 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35371 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.68980 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.close()
		
			//// Rectangle 45 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88414 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.78362 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76628 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 3
			//// Rectangle 1 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23569 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.close()
		
			//// Rectangle 14 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29479 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.close()
		
			//// Rectangle 24 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.40834 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88412 * rect.width, y: rect.minY + 0.50219 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.99810 * rect.width, y: rect.minY + 0.31450 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.94304 * rect.width, y: rect.minY + 0.22065 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.40834 * rect.height))
		path.close()
		
			//// Rectangle 31 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70720 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.50214 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58935 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.close()
		
			//// Rectangle 42 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.78365 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41261 * rect.width, y: rect.minY + 0.87750 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53046 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47153 * rect.width, y: rect.minY + 0.59596 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.78365 * rect.height))
		path.close()
		
			//// Rectangle 44 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76611 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.78362 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64826 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 4
			//// Rectangle 4 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35371 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.close()
		
			//// Rectangle 9 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88414 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.22066 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76628 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.close()
		
			//// Rectangle 17 Drawing
		path.move(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11785 * rect.width, y: rect.minY + 0.59601 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17678 * rect.width, y: rect.minY + 0.50217 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.05893 * rect.width, y: rect.minY + 0.31448 * rect.height))
		path.line(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.close()
		
			//// Rectangle 27 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41262 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.59597 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.close()
		
			//// Rectangle 34 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82503 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.50214 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70718 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.close()
		
			//// Rectangle 47 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.97132 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64829 * rect.width, y: rect.minY + 0.87748 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53044 * rect.width, y: rect.minY + 0.68979 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 0.78363 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.97132 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 5
			//// Rectangle 2 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29479 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.22066 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.close()
		
			//// Rectangle 12 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.22069 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88412 * rect.width, y: rect.minY + 0.31453 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.99810 * rect.width, y: rect.minY + 0.12684 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.94304 * rect.width, y: rect.minY + 0.03300 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.22069 * rect.height))
		path.close()
		
			//// Rectangle 19 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70720 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.31449 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58935 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.close()
		
			//// Rectangle 30 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41261 * rect.width, y: rect.minY + 0.68984 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53046 * rect.width, y: rect.minY + 0.50215 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47153 * rect.width, y: rect.minY + 0.40831 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.close()
		
			//// Rectangle 32 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76611 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.59597 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64826 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.close()
		
			//// Rectangle 37 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23569 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.68980 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 6
			//// Rectangle 11 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.40836 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64829 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53044 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 0.22067 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.40836 * rect.height))
		path.close()
		
			//// Rectangle 16 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.50218 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35371 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.31449 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.40833 * rect.height))
		path.close()
		
			//// Rectangle 21 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88414 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76628 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.close()
		
			//// Rectangle 29 Drawing
		path.move(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.59598 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11785 * rect.width, y: rect.minY + 0.78367 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17678 * rect.width, y: rect.minY + 0.68982 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.05893 * rect.width, y: rect.minY + 0.50213 * rect.height))
		path.line(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.59598 * rect.height))
		path.close()
		
			//// Rectangle 39 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41262 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.78362 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.close()
		
			//// Rectangle 46 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82503 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.68980 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70718 * rect.width, y: rect.minY + 0.78364 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.87749 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 7
			//// Rectangle 7 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70720 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58935 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64827 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.close()
		
			//// Rectangle 18 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.40834 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41261 * rect.width, y: rect.minY + 0.50219 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53046 * rect.width, y: rect.minY + 0.31450 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47153 * rect.width, y: rect.minY + 0.22065 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35368 * rect.width, y: rect.minY + 0.40834 * rect.height))
		path.close()
		
			//// Rectangle 20 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76611 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64826 * rect.width, y: rect.minY + 0.50216 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70719 * rect.width, y: rect.minY + 0.59600 * rect.height))
		path.close()
		
			//// Rectangle 25 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23569 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17676 * rect.width, y: rect.minY + 0.50214 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11783 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.close()
		
			//// Rectangle 38 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.97131 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29479 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23587 * rect.width, y: rect.minY + 0.78362 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17694 * rect.width, y: rect.minY + 0.87747 * rect.height))
		path.close()
		
			//// Rectangle 48 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.78365 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88412 * rect.width, y: rect.minY + 0.87750 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.99810 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.94304 * rect.width, y: rect.minY + 0.59596 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82519 * rect.width, y: rect.minY + 0.78365 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}

struct Grid8jShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 8
			//// Rectangle 3 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.40835 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.41262 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35370 * rect.width, y: rect.minY + 0.22066 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29477 * rect.width, y: rect.minY + 0.31451 * rect.height))
		path.close()
		
			//// Rectangle 10 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82503 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.12683 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.70718 * rect.width, y: rect.minY + 0.22068 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76610 * rect.width, y: rect.minY + 0.31452 * rect.height))
		path.close()
		
			//// Rectangle 23 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.59601 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.64829 * rect.width, y: rect.minY + 0.50217 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53044 * rect.width, y: rect.minY + 0.31448 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 0.40832 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.58936 * rect.width, y: rect.minY + 0.59601 * rect.height))
		path.close()
		
			//// Rectangle 28 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.68983 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.35371 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.29478 * rect.width, y: rect.minY + 0.50214 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.23586 * rect.width, y: rect.minY + 0.59599 * rect.height))
		path.close()
		
			//// Rectangle 33 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.88414 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.59597 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.76628 * rect.width, y: rect.minY + 0.68981 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.82521 * rect.width, y: rect.minY + 0.78366 * rect.height))
		path.close()
		
			//// Rectangle 41 Drawing
		path.move(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.78363 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.11785 * rect.width, y: rect.minY + 0.97132 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.17678 * rect.width, y: rect.minY + 0.87748 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.05893 * rect.width, y: rect.minY + 0.68979 * rect.height))
		path.line(to: NSPoint(x: rect.minX + -0.00000 * rect.width, y: rect.minY + 0.78363 * rect.height))
		path.close()
		
		return Path(path.cgPath)
	}
}


struct Grid8jLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group 9
			//// Bezier Drawing
		path.move(to: NSPoint(x: rect.minX + 0.05898 * rect.width, y: rect.minY + 0.00203 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.05898 * rect.width, y: rect.minY + 1.00000 * rect.height))
		
			//// Bezier 2 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 0.00203 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.47151 * rect.width, y: rect.minY + 1.00000 * rect.height))
		
			//// Bezier 3 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.53045 * rect.width, y: rect.minY + 0.00203 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.53045 * rect.width, y: rect.minY + 1.00000 * rect.height))
		
			//// Bezier 4 Drawing
		path.move(to: NSPoint(x: rect.minX + 0.94298 * rect.width, y: rect.minY + 0.00203 * rect.height))
		path.line(to: NSPoint(x: rect.minX + 0.94298 * rect.width, y: rect.minY + 1.00000 * rect.height))
		
		return Path(path.cgPath)
	}
}
