//
//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16uShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.22223 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.05568 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.00012 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.33321 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.27766 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.66637 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.61081 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.44426 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.83304 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.72192 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.22223 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.55538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.33327 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.72205 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.61093 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.94414 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.99970 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.83316 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.77760 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.94414 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.22217 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.16661 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.22217 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.55538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.33327 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.72192 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.66636 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.61081 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.72192 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.99952 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.94396 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.77741 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.05568 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.22223 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.00012 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.05568 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.38890 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.38890 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.61081 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.66637 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.44426 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.61081 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.83309 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.77754 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.83309 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.11118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.11118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.05562 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.11118 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.33328 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.38884 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.22216 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.33328 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.55538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.61093 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.72204 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.83316 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.77760 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.66648 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.72204 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.22229 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.27785 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.11117 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.22229 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.55550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.44439 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.49994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.55550 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.61087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.72199 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.66643 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.55531 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.61087 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.94421 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.83309 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.33322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.27766 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.11111 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.77754 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.61099 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.55544 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.94408 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.99964 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.88853 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.94408 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.16679 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.22235 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.11124 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.05568 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.16679 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.27784 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.44439 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.22229 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.27784 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.61087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.49976 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.88853 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.66642 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.11112 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.16668 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.05556 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.11112 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.33321 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.27766 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.61100 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.55544 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.44432 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.83304 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.72192 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.22223 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.38871 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.49983 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.44427 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.33315 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.38871 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.72205 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.61093 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.88859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.94415 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.83303 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.77747 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.88859 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.22217 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.22217 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.16661 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.22217 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.44427 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.49983 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.38871 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.33315 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.44427 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.66636 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.61081 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.72192 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.77748 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.83303 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.94415 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.88859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.77747 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.83303 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.05556 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.16668 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.11112 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.05556 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.38890 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.27778 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.33334 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.55544 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.61100 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.44432 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.55544 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.77754 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.83309 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.11118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.05562 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.11118 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.44439 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.27784 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.22229 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.61093 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.66649 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.55538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.49982 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.61093 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.88853 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.66642 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.27766 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.33322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64639 * frame.width, y: frame.minY + 0.16667 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58760 * frame.width, y: frame.minY + 0.11111 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41137 * frame.width, y: frame.minY + 0.27766 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.49994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23495 * frame.width, y: frame.minY + 0.55550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35253 * frame.width, y: frame.minY + 0.44439 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29374 * frame.width, y: frame.minY + 0.38883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17616 * frame.width, y: frame.minY + 0.49994 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.61099 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.94012 * frame.width, y: frame.minY + 0.77754 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99891 * frame.width, y: frame.minY + 0.72198 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.55544 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.61099 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.94421 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.23515 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17636 * frame.width, y: frame.minY + 0.83309 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11757 * frame.width, y: frame.minY + 0.88865 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.27785 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.22229 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.11117 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.16673 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.49988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.38877 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.44433 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.66643 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.72199 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.61087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.55531 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.66643 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.99964 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.88853 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.83297 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.94408 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.99964 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 255.0 / 270)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.16679 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.22235 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.82268 * frame.width, y: frame.minY + 0.11124 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.76389 * frame.width, y: frame.minY + 0.05568 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.16679 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41138 * frame.width, y: frame.minY + 0.38884 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.47016 * frame.width, y: frame.minY + 0.33328 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.35259 * frame.width, y: frame.minY + 0.22216 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.29380 * frame.width, y: frame.minY + 0.27772 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.61087 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.70511 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64632 * frame.width, y: frame.minY + 0.49976 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58753 * frame.width, y: frame.minY + 0.55532 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.77760 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.05879 * frame.width, y: frame.minY + 0.83316 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17637 * frame.width, y: frame.minY + 0.72204 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.11758 * frame.width, y: frame.minY + 0.66648 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.77760 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16uLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 270.0)
		
			//// Bezier 20 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06515 * frame.width, y: frame.minY + 0.00013 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06515 * frame.width, y: frame.minY + 0.99961 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.49073 * frame.width, y: frame.minY + 0.00013 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49073 * frame.width, y: frame.minY + 0.99961 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.38194 * frame.width, y: frame.minY + 0.00013 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.38194 * frame.width, y: frame.minY + 0.99961 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.91166 * frame.width, y: frame.minY + 0.00013 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91166 * frame.width, y: frame.minY + 0.99961 * frame.height))
		
		return path
	}
}
