//
//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16sShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06552 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06551 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52429 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06552 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06551 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52429 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06552 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33595 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75378 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67180 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.03493 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.24027 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25397 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.65070 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.24002 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.65046 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.75359 * frame.width, y: frame.minY + 0.85580 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49971 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.83556 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.13735 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.41773 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.33576 * frame.width, y: frame.minY + 0.75337 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.34269 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.54803 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99952 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.75313 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.91754 * frame.width, y: frame.minY + 0.95847 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06551 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.13749 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.03487 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52429 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17200 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06552 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.67175 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52430 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49975 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.02455 * frame.width, y: frame.minY + 0.44536 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06551 * frame.width, y: frame.minY + 0.54798 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14745 * frame.width, y: frame.minY + 0.34273 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.10648 * frame.width, y: frame.minY + 0.24011 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.52429 * frame.width, y: frame.minY + 0.85584 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56526 * frame.width, y: frame.minY + 0.95846 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64720 * frame.width, y: frame.minY + 0.75322 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.65060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16sLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 210.0)
		
			//// Bezier 20 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.08600 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08600 * frame.width, y: frame.minY + 0.99779 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.58575 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.58575 * frame.width, y: frame.minY + 0.99779 * frame.height))
		
		return path
	}
}
