//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid8nShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group
			//// Rectangle 4 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.55250 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.55250 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 15 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 17 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.closeSubpath()
		
		return path
	}
}

struct Grid8nShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 2
			//// Rectangle 1 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.14892 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.14892 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 14 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 18 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.60226 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.closeSubpath()
		
		return path
	}
}

struct Grid8nShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 3
			//// Rectangle 7 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.75440 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.75440 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 21 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 23 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.closeSubpath()
		
		return Path(path.cgPath)
	}
}

struct Grid8nShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 4
			//// Rectangle 10 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.35083 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.35083 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29940 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 20 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 24 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.80417 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.closeSubpath()
		
		return Path(path.cgPath)
	}
}

struct Grid8nShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 5
			//// Rectangle 3 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 5 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 16 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.55250 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.55250 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.65345 * shapeSize))
		path.closeSubpath()
		
		return path
	}
}

struct Grid8nShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 6
			//// Rectangle 2 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.25000 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.55261 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 6 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.65357 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.19869 * shapeSize, y: ancor.y + 0.95619 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 13 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.14892 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.14892 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.24988 * shapeSize))
		path.closeSubpath()
		
		return Path(path.cgPath)
	}
}

struct Grid8nShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 7
			//// Rectangle 9 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 11 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40060 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40060 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 19 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.75440 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.75440 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.85535 * shapeSize))
		path.closeSubpath()
		
		return Path(path.cgPath)
	}
}

struct Grid8nShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 8
			//// Rectangle 8 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40060 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40060 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.45166 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29964 * shapeSize, y: ancor.y + 0.75428 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 12 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50131 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.04809 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.40036 * shapeSize, y: ancor.y + 0.35071 * shapeSize))
		path.closeSubpath()
		
			//// Rectangle 22 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.90512 * shapeSize, y: ancor.y + 0.35083 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.35083 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70321 * shapeSize, y: ancor.y + 0.45178 * shapeSize))
		path.closeSubpath()
		
		return path
	}
}


struct Grid8nLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let shapeSize = rect.width < rect.height * 0.8
		? rect.width
		: rect.height
		let ancor: CGPoint = rect.width < rect.height * 0.8
		? CGPoint(x: 0, y: (rect.height - rect.width) / 2)
		: CGPoint(x: (rect.width - rect.height) / 2, y: 0)
		
			//// Group 9
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.00476 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.09774 * shapeSize, y: ancor.y + 0.99512 * shapeSize))
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.29956 * shapeSize, y: ancor.y + 0.00476 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.29956 * shapeSize, y: ancor.y + 0.99512 * shapeSize))
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.50137 * shapeSize, y: ancor.y + 0.00476 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.50137 * shapeSize, y: ancor.y + 0.99512 * shapeSize))
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: ancor.x + 0.70319 * shapeSize, y: ancor.y + 0.00476 * shapeSize))
		path.addLine(to: CGPoint(x: ancor.x + 0.70319 * shapeSize, y: ancor.y + 0.99512 * shapeSize))
		
		return Path(path.cgPath)
	}
}
