//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16fShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06372 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06372 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18829 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18829 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62435 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62435 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99806 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99806 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37522 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37522 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93585 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93585 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49978 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49978 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81128 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81128 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18815 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49964 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18829 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18829 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62435 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62435 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56200 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12593 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06358 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62421 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06372 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06372 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.76700 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.07340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68657 * frame.width, y: frame.minY + 0.42020 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49978 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49978 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81128 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81128 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74892 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43743 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37507 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81114 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37522 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37522 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93585 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93585 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87349 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31286 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25050 * frame.width, y: frame.minY + 0.94060 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99806 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99806 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.24700 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93570 * frame.width, y: frame.minY + 0.59380 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16fLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 125.0)
		
			//// Bezier 20 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00136 * frame.width, y: frame.minY + 0.99777 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.25054 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25054 * frame.width, y: frame.minY + 0.99777 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.49972 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49972 * frame.width, y: frame.minY + 0.99777 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.74889 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74889 * frame.width, y: frame.minY + 0.99777 * frame.height))
		
		return path
	}
}
