//
//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16vShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.34948 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.39949 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.09992 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56287 * frame.width, y: frame.minY + 0.04991 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.34948 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.44944 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.49939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.49939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.44944 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.49947 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95271 * frame.width, y: frame.minY + 0.79904 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99608 * frame.width, y: frame.minY + 0.74903 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73630 * frame.width, y: frame.minY + 0.44946 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.49947 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.24978 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34639 * frame.width, y: frame.minY + 0.29979 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56294 * frame.width, y: frame.minY + 0.05007 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51957 * frame.width, y: frame.minY + 0.00006 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.24978 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.44940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95278 * frame.width, y: frame.minY + 0.69911 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99614 * frame.width, y: frame.minY + 0.64911 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77959 * frame.width, y: frame.minY + 0.39939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.44940 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.05007 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95278 * frame.width, y: frame.minY + 0.29979 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99614 * frame.width, y: frame.minY + 0.24978 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77959 * frame.width, y: frame.minY + 0.00006 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.05007 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.64911 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34639 * frame.width, y: frame.minY + 0.69911 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56294 * frame.width, y: frame.minY + 0.44940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51957 * frame.width, y: frame.minY + 0.39939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.64911 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.09992 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95271 * frame.width, y: frame.minY + 0.39949 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99608 * frame.width, y: frame.minY + 0.34948 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73630 * frame.width, y: frame.minY + 0.04991 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.09992 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.74903 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.79904 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.49947 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56287 * frame.width, y: frame.minY + 0.44946 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.74903 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.19978 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60616 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64952 * frame.width, y: frame.minY + 0.24962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56293 * frame.width, y: frame.minY + 0.14977 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.19978 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.49939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77951 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.94883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.44944 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56298 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64959 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.84895 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.24962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95278 * frame.width, y: frame.minY + 0.49934 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99614 * frame.width, y: frame.minY + 0.44933 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77959 * frame.width, y: frame.minY + 0.19961 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.24962 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.84888 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34639 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56294 * frame.width, y: frame.minY + 0.64917 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51957 * frame.width, y: frame.minY + 0.59916 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.84888 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.29970 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95271 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99608 * frame.width, y: frame.minY + 0.54925 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73630 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.29970 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.94880 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.99881 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.69925 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56287 * frame.width, y: frame.minY + 0.64924 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.94880 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77951 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.74908 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.79910 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60616 * frame.width, y: frame.minY + 0.89896 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64952 * frame.width, y: frame.minY + 0.84895 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56293 * frame.width, y: frame.minY + 0.74909 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.79910 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56298 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64959 * frame.width, y: frame.minY + 0.44945 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.44945 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.44945 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.04994 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.44945 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.44945 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56298 * frame.width, y: frame.minY + 0.74907 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64959 * frame.width, y: frame.minY + 0.84895 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.74907 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.34957 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.39955 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60616 * frame.width, y: frame.minY + 0.49941 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64952 * frame.width, y: frame.minY + 0.44940 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56293 * frame.width, y: frame.minY + 0.34954 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.39955 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.49938 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.74908 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.74908 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77951 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.74908 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.54925 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60623 * frame.width, y: frame.minY + 0.29970 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56287 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30309 * frame.width, y: frame.minY + 0.54925 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.59926 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.69925 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95271 * frame.width, y: frame.minY + 0.99881 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99608 * frame.width, y: frame.minY + 0.94880 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73630 * frame.width, y: frame.minY + 0.64924 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69293 * frame.width, y: frame.minY + 0.69925 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.44933 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34639 * frame.width, y: frame.minY + 0.49934 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56294 * frame.width, y: frame.minY + 0.24962 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51957 * frame.width, y: frame.minY + 0.19961 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30302 * frame.width, y: frame.minY + 0.44933 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.64917 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.95278 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99614 * frame.width, y: frame.minY + 0.84888 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77959 * frame.width, y: frame.minY + 0.59916 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73623 * frame.width, y: frame.minY + 0.64917 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56298 * frame.width, y: frame.minY + 0.14981 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64959 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.14981 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.09988 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.44944 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.24969 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.84895 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.64920 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.14981 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60628 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.69290 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.77951 * frame.width, y: frame.minY + 0.19975 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.73620 * frame.width, y: frame.minY + 0.14981 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.21653 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.29963 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17322 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.30314 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34645 * frame.width, y: frame.minY + 0.49939 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.39951 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.59933 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.60616 * frame.width, y: frame.minY + 0.69918 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64952 * frame.width, y: frame.minY + 0.64917 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56293 * frame.width, y: frame.minY + 0.54932 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.51956 * frame.width, y: frame.minY + 0.59933 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12992 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.69914 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.17323 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.04331 * frame.width, y: frame.minY + 0.94883 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.89889 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.79901 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16vLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 260.0 / 220.0)
		
			//// Bezier 33 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.01971 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.08661 * frame.width, y: frame.minY + 0.94883 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.01971 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25984 * frame.width, y: frame.minY + 0.94883 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.43306 * frame.width, y: frame.minY + 0.01971 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43306 * frame.width, y: frame.minY + 0.94883 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.86612 * frame.width, y: frame.minY + 0.01971 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.86612 * frame.width, y: frame.minY + 0.94883 * frame.height))
		
		return path
	}
}
