//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16hShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.00931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.15086 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.34702 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34702 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64446 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64446 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.15086 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.00931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24793 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34701 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24793 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64447 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74355 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64447 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.29232 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.57538 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14885 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24793 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14885 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74355 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84263 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74355 * frame.width, y: frame.minY + 0.99857 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.00931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.15086 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64745 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.84276 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99607 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84666 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84276 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.57549 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14872 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14872 * frame.width, y: frame.minY + 0.99849 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.15086 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.85859 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49804 * frame.width, y: frame.minY + 0.00931 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.15085 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34863 * frame.width, y: frame.minY + 0.29240 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.43395 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.57550 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14941 * frame.width, y: frame.minY + 0.71704 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.14954 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.84653 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.15088 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.29249 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.43393 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.57555 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.34861 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24908 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74699 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.71699 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.64746 * frame.width, y: frame.minY + 0.85861 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16hLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 220.0 / 300.0)
		
			//// Bezier 20 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.07471 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.07471 * frame.width, y: frame.minY + 0.97716 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.42333 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.42333 * frame.width, y: frame.minY + 0.97716 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.57274 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.57274 * frame.width, y: frame.minY + 0.97716 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.92137 * frame.width, y: frame.minY + 0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.92137 * frame.width, y: frame.minY + 0.97716 * frame.height))
		
		return path
	}
}
