//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16gShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 21 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 22 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 23 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 24 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 25 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.03340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 26 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 27 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 28 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.03340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 29 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37405 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62318 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 30 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31166 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68557 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 31 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.24927 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18688 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81035 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74796 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 32 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.50627 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.12796 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.31712 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18703 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12464 * frame.width, y: frame.minY + 0.88481 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87260 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.50650 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81020 * frame.width, y: frame.minY + 0.69565 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 33 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.03340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 34 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99725 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87259 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62328 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 35 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.97935 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 36 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00000 * frame.width, y: frame.minY + 0.03340 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.22259 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12466 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49862 * frame.width, y: frame.minY + 0.41178 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.60097 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37397 * frame.width, y: frame.minY + 0.79016 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16gLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 340.0 / 225.0)
		
			//// Bezier 20 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06233 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06233 * frame.width, y: frame.minY + 0.99952 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.43629 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43629 * frame.width, y: frame.minY + 0.99952 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.56095 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56095 * frame.width, y: frame.minY + 0.99952 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.93492 * frame.width, y: frame.minY + -0.00000 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93492 * frame.width, y: frame.minY + 0.99952 * frame.height))
		
		return path
	}
}
