//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Grid16jShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 1 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 2 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 3 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 4 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape5: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 5 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape6: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 6 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape7: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 7 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99775 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99775 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape8: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 8 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49819 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49819 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape9: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 9 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.50094 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape10: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 10 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.31370 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.56051 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape11: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 11 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.25123 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.62297 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape12: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 12 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.18877 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.68543 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape13: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 13 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.12630 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.74790 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape14: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 14 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.06384 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00138 * frame.width, y: frame.minY + 0.77500 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.06500 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.81036 * frame.width, y: frame.minY + 0.42417 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape15: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 15 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49819 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49819 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87283 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jShape16: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 16 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.43862 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37616 * frame.width, y: frame.minY + 0.95458 * frame.height))
		path.closeSubpath()
		path.move(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99775 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.99775 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.24458 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.93529 * frame.width, y: frame.minY + 0.59542 * frame.height))
		path.closeSubpath()
		
		return path
	}
}

struct Grid16jLine: Shape {
	func path(in rect: CGRect) -> Path {
		
		var path = Path()
		let frame: CGRect = rect.fitRect(ratio: 345.0 / 120.0)
		
			//// Bezier 55 Drawing
		path.move(to: CGPoint(x: frame.minX + 0.00145 * frame.width, y: frame.minY + 0.00010 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.00145 * frame.width, y: frame.minY + 0.99667 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.37504 * frame.width, y: frame.minY + 0.00010 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.37504 * frame.width, y: frame.minY + 0.99667 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.49957 * frame.width, y: frame.minY + 0.00010 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.49957 * frame.width, y: frame.minY + 0.99667 * frame.height))
		path.move(to: CGPoint(x: frame.minX + 0.87316 * frame.width, y: frame.minY + 0.00010 * frame.height))
		path.addLine(to: CGPoint(x: frame.minX + 0.87316 * frame.width, y: frame.minY + 0.99667 * frame.height))
		
		return path
	}
}

