//
//  StyleKitName.swift
//  ProjectName
//
//  Created by AuthorName on 12.01.2025.
//  Copyright © 2025 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//


import SwiftUI

struct Scheme4aShape1: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
		path.appendOval(in: NSRect(x: 46.15, y: 94.85, width: 120, height: 120))
		
		path.appendOval(in: NSRect(x: 235.4, y: 95.15, width: 120, height: 120))

		return Path(path.cgPath)
	}
}

struct Scheme4aShape2: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
		
			//// Group 3
			//// Oval 2 Drawing
		path.appendOval(in: NSRect(x: 114.85, y: 78, width: 8, height: 8))
		
			//// Oval 3 Drawing
		path.appendOval(in: NSRect(x: 89.45, y: 223.7, width: 8, height: 8))
		
			//// Oval 4 Drawing
		path.appendOval(in: NSRect(x: 177.2, y: 150.85, width: 8, height: 8))
		
			//// Oval 5 Drawing
		path.appendOval(in: NSRect(x: 26.5, y: 150.85, width: 8, height: 8))
		
			//// Oval 7 Drawing
		path.appendOval(in: NSRect(x: 218.55, y: 163.85, width: 8, height: 8))
		
			//// Oval 8 Drawing
		path.appendOval(in: NSRect(x: 364.2, y: 138.45, width: 8, height: 8))
		
			//// Oval 9 Drawing
		path.appendOval(in: NSRect(x: 291.4, y: 226.2, width: 8, height: 8))
		
			//// Oval 10 Drawing
		path.appendOval(in: NSRect(x: 291.4, y: 75.5, width: 8, height: 8))
		
		return Path(path.cgPath)
	}
}

struct Scheme4aShape3: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()
		
			//// Group
			//// Bezier Drawing
		path.move(to: NSPoint(x: 118.86, y: 86.02))
		path.line(to: NSPoint(x: 118.86, y: 226.39))
		
			//// Bezier 3 Drawing
		path.move(to: NSPoint(x: 93.45, y: 223.68))
		path.line(to: NSPoint(x: 93.45, y: 83.32))
		
			//// Bezier 5 Drawing
		path.move(to: NSPoint(x: 226.55, y: 167.86))
		path.line(to: NSPoint(x: 366.91, y: 167.86))
		
			//// Bezier 7 Drawing
		path.move(to: NSPoint(x: 364.21, y: 142.45))
		path.line(to: NSPoint(x: 223.84, y: 142.45))
		
		return Path(path.cgPath)
	}
}

struct Scheme4aShape4: Shape {
	func path(in rect: CGRect) -> Path {
		
		let path = NSBezierPath()

			//// Group 2
			//// Bezier 2 Drawing
		path.move(to: NSPoint(x: 118.86, y: 231.68))
		path.line(to: NSPoint(x: 115.81, y: 224.22))
		path.line(to: NSPoint(x: 118.86, y: 225.99))
		path.line(to: NSPoint(x: 121.91, y: 224.22))
		path.line(to: NSPoint(x: 118.86, y: 231.68))
		
			//// Bezier 4 Drawing
		path.move(to: NSPoint(x: 93.45, y: 78.02))
		path.line(to: NSPoint(x: 96.5, y: 85.48))
		path.line(to: NSPoint(x: 93.45, y: 83.71))
		path.line(to: NSPoint(x: 90.41, y: 85.48))
		path.line(to: NSPoint(x: 93.45, y: 78.02))
		
			//// Bezier 6 Drawing
		path.move(to: NSPoint(x: 372.21, y: 167.86))
		path.line(to: NSPoint(x: 364.75, y: 170.91))
		path.line(to: NSPoint(x: 366.52, y: 167.86))
		path.line(to: NSPoint(x: 364.75, y: 164.81))
		path.line(to: NSPoint(x: 372.21, y: 167.86))
		
		
			//// Bezier 8 Drawing
		path.move(to: NSPoint(x: 218.55, y: 142.45))
		path.line(to: NSPoint(x: 226.01, y: 139.4))
		path.line(to: NSPoint(x: 224.24, y: 142.45))
		path.line(to: NSPoint(x: 226.01, y: 145.5))
		path.line(to: NSPoint(x: 218.55, y: 142.45))
		
		return Path(path.cgPath)
	}
}
